# Generated by Django 4.1.2 on 2022-10-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_name", models.CharField(max_length=50)),
                ("nse_code", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=30)),
                ("desc", models.CharField(max_length=100)),
                ("ends_in", models.DateField()),
                ("room_money", models.IntegerField()),
                (
                    "reg_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Join",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_money", models.FloatField()),
                (
                    "reg_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.profile"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Stock_Game.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Buy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_stock_price", models.FloatField()),
                ("no_of_shares", models.IntegerField()),
                (
                    "reg_room_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Stock_Game.room",
                    ),
                ),
                (
                    "reg_stock_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Stock_Game.stock",
                    ),
                ),
                (
                    "reg_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.profile"
                    ),
                ),
            ],
        ),
    ]
