# Generated by Django 4.1.2 on 2024-01-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_Game', '0002_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='top_stock',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
