# Generated by Django 4.1.2 on 2024-01-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_Game', '0003_ratings_top_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
